### ISSUE TITLE
Can't do the "Meet Darla" activity in The Midway 1

### ISSUE THREAD

**Issue by BlitzGH** [DestinationHome/Destination-Home-Online#295]
Title.

**Comment by xJeris** [comment]
@BlitzGH Please include the additional information requested below.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots & Video Documentation**
If applicable, add screenshots or videos to help explain your problem. This will allow the Destination Home team to fix critical bugs faster for our community. 

# Client Information:
**Region:** [SCEA, SCEE, SCEJ, SCEAsia, Other]
**Country:** 
**Platform:** [PS3, RPCS3]
**Firmware Type:** [OFW, HFW, CFW]

**Additional context**
Add any other context about the problem here, that you may see fit to give a general overview of this issue.

**Comment by xJeris** [comment]
Closing since no info was ever given.
