### ISSUE TITLE
Red Bull House of Skate_Personal Space/mini game does not start

### ISSUE THREAD

**Issue by kon-aki** [DestinationHome/Destination-Home-Online#50]
**Describe the bug**
The mini-games "Red Bull Skateboarding" and "Red Bull Vending Machine" are not playable.

**To Reproduce**

1. Go to '"Red Bull Skateboarding" and "Red Bull Vending Machine" '
2. Click on 'play'
![IMG_02](https://user-images.githubusercontent.com/118769591/203379356-8ea6df0c-5084-41b1-80cf-b5222664f215.jpg)
![IMG_01](https://user-images.githubusercontent.com/118769591/203379402-b2124c0b-bb3a-4372-889c-e39221462e25.jpg)

**Expected behavior**
Normally, the respective mini-game will be activated.

# Client Information:
**Region:** [SCEA]
**Country:** Japan
**Platform:** [PS3]
**Firmware Type:** [OFW]

**Comment by NagatoDEV** [comment]
# <h1 align="center">**Bug Report**: Fixing Red Bull Skating & Red Bull Vending Machine Minigames for Red Bull House Of Skate</h1>

![NPIA00005_screenshot_2022_12_10_17_27_20](https://user-images.githubusercontent.com/67494727/206877625-f399c9f6-87d1-4a5c-8733-32b12f957985.png)

Both minigames (**Red Bull Skating** & **
![Uploading NPIA00005_screenshot_2022_12_10_17_20_56.png…]()
Red Bull Vending Machine**) for Red Bull House of Skate should be fixed. Users will need to **clear cache** in order to see any changes. I've tested on the NA/US region. @kon-aki 

# <h2 align="center">Fixed minigames:</h2>

![NPIA00005_screenshot_2022_12_10_17_18_46](https://user-images.githubusercontent.com/67494727/206877783-48fa2d65-9741-4957-90f3-abf61fb5a89d.png)
![NPIA00005_screenshot_2022_12_10_17_19_11](https://user-images.githubusercontent.com/67494727/206877822-57c110c8-f0b4-4a28-97c3-2a68bbf6c62c.png)


**Client Tested:** RPCS3
**Region:** NA 
**Notes:** Haven't tested on PS3 however, PS3 users should be fine once you clear cache.
