### ISSUE TITLE
Fearless Records Boombox_ Appliances/Not Activated

### ISSUE THREAD

**Issue by kon-aki** [DestinationHome/Destination-Home-Online#55]
**Describe the bug**
It can be placed, but it will not start.

**To Reproduce**

1. Go to 'Fearless Records Boombox'
2. Click on 'play'

**Expected behavior**
Normally, several types of background music are built in and can be selected for playback.

**Screenshots & Video Documentation**
![IMG_13](https://user-images.githubusercontent.com/118769591/203385960-e2d7e27a-3b9b-4827-a913-abd3a4a818d6.jpg)

# Client Information:
**Region:** [SCEA]
**Country:** japan
**Platform:** [PS3]
**Firmware Type:** [OFW]

**Additional context**
Is it possible that the copyright of Fearless Records could be affected, making it unrecoverable?

**Comment by NagatoDEV** [comment]
# <h1 align="center">**Bug Report**: Fixing The Fearless Records Boombox Music Player</h1>

![NPIA00005_screenshot_2022_12_12_16_00_20](https://user-images.githubusercontent.com/67494727/207156418-3d1cef19-6825-491d-970a-32c2f33fc0f4.png)

The minigame **Fearless Records Music Player** is fixed now Users will need to **clear cache** in order to see any changes. I've tested on the NA/US region. @kon-aki 

# <h2 align="center">Fixed minigames:</h2>

https://user-images.githubusercontent.com/67494727/207156589-1c7ac80a-e15e-480f-8809-b457e1b2bcf8.mp4

**Client Tested:** RPCS3
**Region:** NA 
**Notes:** Haven't tested on PS3 however, PS3 users should be fine once you clear cache.
