### ISSUE TITLE
Playground music doesn't play for some users

### ISSUE THREAD

**Issue by I-Knight-I** [DestinationHome/Destination-Home-Online#6]
**Describe the bug**

The music at The Playground doesn't play for certain users. No pattern or common factors identified.

**To Reproduce**

1. ???
2. Go to The Playground
3. Go to the stage area
4. No music

**Expected behavior**

Music should be playing

**Comment by NagatoDEV** [comment]
# <h1 align="center">**Bug Report**: Original Playground Music Player</h1>

@TheOrbOfDestiny @I-Knight-I 

Original Playground Music Player should be fixed. Users will need to **clear cache** in order to see any changes. I've tested on both regions: NA & Great Britain (EU) & music is playing as shown below.

# <h2 align="center">The PlayGround (NA Region)</h2>

https://user-images.githubusercontent.com/67494727/198285998-330114d9-007e-4b22-b29b-1a9e7a29a656.mp4

# <h2 align="center">The PlayGround (EU Region)</h2>

https://user-images.githubusercontent.com/67494727/198286039-513cbf81-2dde-4230-b3e4-fbac1766a503.mp4

**Client Tested:** RPCS3
**Region:** NA & EU
**Notes:** Haven't tested on PS3 however since I've re-routed to EU on RPCS3 manually PS3 users should be fine once you clear cache.
